In [1]:
import pandas as pd

In [7]:
df = pd.read_csv('Predictions.csv')
def predict_result(spread: int):
    if spread>0:
        return 1
    else:
        return 0

In [ ]:
df['Predicted_Result'] = df['SPREAD_PREDICTIONS'].apply(predict_result)
df['Actual_result'] = [1,1,1,1,1,0,1,0,0,1,0,0,0,1,0,1,0,x,x,x]

   predictions_final.game_matchup  SPREAD_PREDICTIONS  Predicted_Result
0                       ATL @ IND           21.232683                 1
1                       ATL @ MIN            9.798152                 1
2                       BKN @ NYK           11.323067                 1
3                       BKN @ PHI           -4.826933                 0
4                       BOS @ MIL           16.636267                 1
5                       CHA @ ATL           26.474088                 1
6                       CHA @ BOS           21.454373                 1
7                       CHA @ CLE           18.272817                 1
8                       CHI @ DET            5.110633                 1
9                       CHI @ NYK           12.215348                 1
10                      CHI @ WAS           -4.429567                 0
11                      DAL @ CHA          -13.856583                 0
12                      DAL @ MIA           -2.691333                 0
13                      DAL @ OKC            5.064167                 1
14                      DEN @ MEM           -6.812726                 0
15                      DEN @ SAS           -9.032848                 0
16                      DEN @ UTA            6.920817                 1
17                      DET @ DAL           10.258814                 1
18                      DET @ PHI           12.715745                 1
19                      DET @ SAS           -1.352898                 0
20                      GSW @ LAL           -5.050950                 0
21                      GSW @ POR           -7.568281                 0
22                      HOU @ LAC            3.925638                 1
23                      HOU @ POR          -13.155617                 0
24                      HOU @ UTA            0.691162                 1
25                      IND @ CLE           -4.727250                 0
26                      IND @ TOR           -3.987629                 0
27                      LAC @ PHX           -6.014486                 0
28                      LAL @ MEM          -10.112017                 0
29                      LAL @ NOP           15.121358                 1
30                      MEM @ CLE            9.787443                 1
31                      MIA @ ATL           -4.127983                 0
32                      MIL @ OKC            4.439317                 1
33                      MIL @ ORL            8.775750                 1
34                      MIN @ DEN           -6.029119                 0
35                      NOP @ GSW           -1.586043                 0
36                      NOP @ POR          -13.674131                 0
37                      NOP @ SAC           -5.363774                 0
38                      NYK @ BOS           12.022202                 1
39                      NYK @ CHI           -4.561148                 0
40                      ORL @ HOU            6.717700                 1
41                      ORL @ MIL            3.980033                 1
42                      ORL @ PHI            2.629833                 1
43                      PHX @ LAC           -1.911183                 0
44                      PHX @ MIN            5.134698                 1
45                      PHX @ SAC           -2.329443                 0
46                      POR @ SAC            6.494250                 1
47                      SAC @ OKC            9.228790                 1
48                      SAS @ MEM           -2.261683                 0
49                      SAS @ OKC           26.468924                 1
50                      TOR @ BKN            9.326479                 1
51                      TOR @ MIA           10.460350                 1
52                      TOR @ MIA           10.460350                 1
53                      UTA @ GSW           12.815283                 1
54                      UTA @ LAC           12.908333                 1
55                      WAS @ BOS           11.979390                 1
56                      WAS @ MIN           18.627517                 1